[project]
name = "commonforms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.3.0",
    "pypdf2>=3.0.1",
    "pypdfium2==5.0.0b2",
]

[dependency-groups]
dev = [
    "ruff>=0.13.0",
]
